### ISSUE TITLE
Additiona Tags

### ISSUE THREAD

**Issue by Hube2** [bordoni/fakerpress#97]
Don't know if it can be done, but some additional tags when generating posts would be great. For example `<pre>`, `<code>`, `<ins>`, `<del>`, `<dl>`, `<em>`, `<strong>`, and `<a>`.

Great plugin by the way, I just found it and it saved me hours of work that I was about to start on a current project entering a very large amount of test data that I was going to need.

**Comment by bordoni** [comment]
Hi @Hube2, currently there is a JavaScript bug that doesn't allow that to happen, but the Plugin was originally intended to allow this behavior.

The `<em>`, `<a>` and `<strong>` tags are already there, but since they are inline elements it's not on the list. _Note, I should mark it in the interface that it's there._

**Comment by Hube2** [comment]
Thanks, I didn't realize the last three were there, I was looking at what could be selected.

**Comment by bordoni** [comment]
Since we resolved this issue I am closing htis.
